# Generated by Django 5.2.7 on 2026-02-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_userexpencesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpencesmodel',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 16, 14, 11, 484737, tzinfo=datetime.timezone.utc)),
        ),
    ]
