# Generated by Django 5.2.7 on 2026-02-01 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userExpense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpensemodel',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userexpensemodel',
            name='expanse_date',
        ),
        migrations.AddField(
            model_name='userexpensemodel',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
