# Generated by Django 5.2.7 on 2026-01-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
